### ISSUE TITLE
INFLUX and Speedy not communicating

### ISSUE THREAD

**Issue by ndaringer** [stefanwalther/speedy#10]
After docker finished building the images I verified that Grafana and Influx started up fine. They appeared to be running(I could access their web interfaces). I noticed that Speedy was not feeding data into influxdb. Both grafana was complaining that there was no data in the db and Influx didn't show the database when I queried it from the web interface.

I checked the docker log for speedy and saw the following error.

>  Error: Cannot find module 'influx'
> Require stack:
> \- /home/src/index.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:859:27)
>     at Module.require (internal/modules/cjs/loader.js:1036:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/home/src/index.js:1:16)
>     at Module._compile (internal/modules/cjs/loader.js:1147:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
>     at Module.load (internal/modules/cjs/loader.js:996:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/home/src/index.js' ]
> }

I am using a fresh pull of the repo as of this morning.

**Comment by samuelhwilliams** [comment]
I'm getting the same error in my speedy logs. :(

**Comment by pjankovsky** [comment]
I've fixed it on my fork: https://github.com/pjankovsky/speedy

Its caused by the local `docker/speedy` directory being mounted over `/home` in the container. That was hiding / removing the installed `node_modules`.

I have yet to figure out how to get grafana to setup the `speed-tests.json` dashboard automatically, but manually importing the json file works fine.
